setwd("C:/Users/18904/Github/ED4DSE/codes")
if(!dir.exists("data"))dir.create("data")
if(!dir.exists("../figures"))dir.create("../figures")
if(!file.exists("data/2.6-plot.RData")){
  f=function(x)sin(10*pi*x)/(1+64*(x-.25)^2)+x^2
  test=seq(0,1,length=301)
  true=f(test)
  set.seed(5)
  n=10;r=2
  D=((1:n)-1)/(n-1)
  D=rep(D,r)
  e=rnorm(n*r,sd=.1)
  y=f(D)+e
  u=seq(0,1,length=301)
  us=2*u-1
  d=2*D-1
  i=3
  a.lm=lm(y~poly(d,i))
  pred1=predict(a.lm,newdata=data.frame(d=us),interval="confidence")
  mean1=pred1[,1];low1=pred1[,2];up1=pred1[,3]
  i=8
  a.lm=lm(y~poly(d,i))
  pred2=predict(a.lm,newdata=data.frame(d=us),interval="confidence")
  mean2=pred2[,1];low2=pred2[,2];up2=pred2[,3]
  save(D,y,test,true,mean1,low1,up1,mean2,low2,up2,file="data/2.6-plot.RData")
}
load("data/2.6-plot.RData")
pdf("../figures/2.6.pdf",width=8,height=4)
par(mfrow=c(1,2))
plot(test,true,type="l",lty=2,xlab="x",ylab="y",ylim=c(min(true)-.25,max(true)+.25),main="3rd Degree (Equi-spaced)")
points(D,y,pch=16,col="blue")
lines(test,mean1,col=3)
polygon(c(test,rev(test)),c(low1,rev(up1)),col=adjustcolor("red",0.2),border=NA)
legend("bottomright",legend=c("truth","prediction"),lty=c(2,1),col=c(1,3),bty="n")
plot(test,true,type="l",lty=2,xlab="x",ylab="y",ylim=c(min(true)-.25,max(true)+.25),main="8th Degree (Equi-spaced)")
points(D,y,pch=16,col="blue")
lines(test,mean2,col=3)
polygon(c(test,rev(test)),c(low2,rev(up2)),col=adjustcolor("red",0.2),border=NA)
dev.off()
