setwd("C:/Users/18904/Github/ED4DSE/codes")
if(!dir.exists("data"))dir.create("data")
if(!dir.exists("../figures"))dir.create("../figures")
if(!file.exists("data/2.8-plot.RData")){
  f=function(x)sin(10*pi*x)/(1+64*(x-.25)^2)+x^2
  test=seq(0,1,length=301)
  true=f(test)
  set.seed(5)
  n=10;re=2
  D1=((1:n)-1)/(n-1)
  D1=rep(D1,re)
  e=rnorm(n*re,sd=.1)
  y1=f(D1)+e
  E1=as.matrix(dist(D1))
  MSCV=function(para,E,y){
    theta=para[1];lam=para[2]
    R=exp(-(E/theta)^2)
    Rinv=solve(R+lam*diag(n*re))
    cv=c(Rinv%*%y)/diag(Rinv)
    log(mean(cv^2))
  }
  GCV=function(para,E,y){
    theta=para[1];lam=para[2]
    R=exp(-(E/theta)^2)
    Rinv=solve(R+lam*diag(n*re))
    cv=c(Rinv%*%y)/mean(diag(Rinv))
    log(mean(cv^2))
  }
  a=optim(c(.1,.1),function(pa)MSCV(pa,E1,y1),lower=c(.05,.001),upper=c(1,1),method="L-BFGS-B")
  theta1=a$par[1];lam1=a$par[2]
  R=exp(-(E1/theta1)^2)
  coef=solve(R+lam1*diag(n*re),y1)
  basis=function(h)exp(-(h/theta1)^2)
  r=function(x)basis(x-D1)
  fhat=function(x)sum(r(x)*coef)
  pred1=test
  for(i in 1:301)pred1[i]=fhat(test[i])
  a=optim(c(.1,.1),function(pa)GCV(pa,E1,y1),lower=c(.05,.001),upper=c(1,1),method="L-BFGS-B")
  theta2=a$par[1];lam2=a$par[2]
  library(AlgDesign)
  cand=data.frame(x=seq(-1,1,length=301))
  a=optFederov(~1+x+I(x^2)+I(x^3)+I(x^4)+I(x^5)+I(x^6)+I(x^7)+I(x^8)+I(x^9),nTrials=n,data=cand,approximate=FALSE)
  D2=rep(c(a$design[,1]),re)
  D2=(D2+1)/2
  y2=f(D2)+e
  E2=as.matrix(dist(D2))
  a=optim(c(.1,.1),function(pa)MSCV(pa,E2,y2),lower=c(.05,.001),upper=c(1,1),method="L-BFGS-B")
  theta3=a$par[1];lam3=a$par[2]
  R=exp(-(E2/theta3)^2)
  coef=solve(R+lam3*diag(n*re),y2)
  basis=function(h)exp(-(h/theta3)^2)
  r=function(x)basis(x-D2)
  fhat=function(x)sum(r(x)*coef)
  pred2=test
  for(i in 1:301)pred2[i]=fhat(test[i])
  save(D1,y1,D2,y2,test,true,pred1,pred2,file="data/2.8-plot.RData")
}
load("data/2.8-plot.RData")
pdf("../figures/2.8.pdf",width=8,height=4)
par(mfrow=c(1,2))
plot(test,true,type="l",lty=2,xlab="x",ylab="y",ylim=c(min(true)-.25,max(true)+.25),main="kernel ridge regression (equi-spaced)")
points(D1,y1,pch=16,col="blue")
lines(test,pred1,col=3)
legend("bottomright",legend=c("truth","prediction"),lty=c(2,1),col=c(1,3),bty="n")
plot(test,true,type="l",lty=2,xlab="x",ylab="y",ylim=c(min(true)-.25,max(true)+.25),main="kernel ridge regression (D-optimal)")
points(D2,y2,pch=16,col="blue")
lines(test,pred2,col=3)
dev.off()
